services:
  strife:
    build:
      args:
        ENVIRONMENT: dev
        PORT: 5000
        USER: strife
        GROUP: darksiders
      context: .
      dockerfile: Dockerfile
    container_name: strife
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - strifenet
      - busnet
      - cachenet
      - dbnet
    secrets:
      - source: db_ca_crt
        target: ca.crt
      - source: db_client_root_key
        target: client.root.key
        mode: 0600
      - source: db_client_root_crt
        target: client.root.crt

networks:
  strifenet:
    driver: bridge